version: "3"

services:
  # worker:
  #   container_name: sttworker
  #   image: sttworker:0.1.01
  #   build:
  #     context: ./sttapp
  #   env_file:
  #     - .env
  #   environment:
  #     - REDIS_HOST=sttredis
  #     - DB_HOST=sttmongo
  #   command: celery -A sttapp.celery_worker.celery worker -l info
  #   restart: "unless-stopped"
  #   volumes:
  #     - ./:/app/
  #   depends_on:
  #     - redis
  #     - mongo
  #   networks:
  #     - redis_network
  #     - mongo_network

  redis:
    container_name: sttredis
    image: redis
    volumes:
      - ./.data/dataRedis/:/data/
    # ports:
    #   - "6379:6379"
    # networks:
    #   - redis_network
    restart: "unless-stopped"
    network_mode: "host"

  mongo:
    container_name: sttmongo
    image: mongo:4.2.6
    volumes:
      - ./.data/dataMongo/:/data/db/
    command: "mongod --auth"
    restart: "unless-stopped"
    # ports:
    #   - "27017:27017"
    # networks:
    #   - mongo_network
    network_mode: "host"
