version: "3"

services:
  flask_app:
    container_name: flask_app
    image: sttapp:0.1.01
    build:
      context: ./sttapp
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: gunicorn -w 1 -b 0.0.0.0:8000 sttapp.wsgi:app
    restart: "unless-stopped"
    volumes:
      - ./:/app/
    network_mode: "host"
    # networks:
    #   - flask_app

  worker:
    container_name: worker
    image: sttworker:0.1.01
    build:
      context: ./sttapp
    env_file:
      - .env
    command: celery -A sttapp.celery_worker.celery worker -l info
    restart: "unless-stopped"
    volumes:
      - ./:/app/
    network_mode: "host"

  nginx:
    image: nginx:1.15.8
    volumes:
      - ./conf.d/:/etc/nginx/conf.d/
    network_mode: "host"
# networks:
#   flask_app:
