version: "3"

services:
  redis:
    container_name: sttredis
    image: redis
    volumes:
      - .data/dataRedis/:/data/
    ports:
      - "6379:6379"
    restart: "unless-stopped"

  mongo:
    container_name: sttmongo
    image: mongo:4.2.6
    volumes:
      - .data/dataMongo/:/data/db/
    command: "mongod --auth"
    ports:
      - "27017:27017"
    restart: "unless-stopped"
