version: "3"

services:
  flask_app:
    container_name: sttapp
    image: sttapp:0.1.01
    build:
      context: ./sttapp
    env_file:
      - .env
    command: gunicorn -w 2 -b 0.0.0.0:8000 -k gevent sttapp.wsgi:app
    restart: "unless-stopped"
    networks:
      - webserver
    volumes:
      - ./:/app/

  nginx:
    container_name: sttnginx
    image: nginx:1.15.8
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./conf.d/:/etc/nginx/conf.d/
      - ./ssl/:/etc/nginx/ssl/
    networks:
      - webserver

  worker:
    container_name: sttworker
    image: sttworker:0.1.01
    build:
      context: ./sttapp
    env_file:
      - .env
    command: celery -A sttapp.celery_worker.celery worker -l info
    restart: "unless-stopped"
    volumes:
      - ./:/app/

networks:
  webserver:
