version: "3"

services:
  flask_app:
    container_name: flask_app
    restart: "unless-stopped"
    build: ./sttapp
    env_file:
      - .env
    command: gunicorn -w 1 -b 0.0.0.0:8000 sttapp.wsgi:server
    networks:
      - backend_redis
      - webserver
    depends_on:
      - redis
    volumes:
      - ./sttapp:/app/sttapp/

  worker:
    container_name: worker
    restart: "unless-stopped"
    build: ./sttapp
    env_file:
      - .env
    networks:
      - backend_redis
    depends_on:
      - redis
    command: celery -A sttapp.celery_worker.celery worker -l info
    volumes:
      - ./sttapp:/app/sttapp/

  nginx:
    container_name: nginx
    restart: "unless-stopped"
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - flask_app
    networks:
      - webserver

  redis:
    container_name: redis
    image: redis
    restart: "unless-stopped"
    volumes:
      - ~/my_volume/dataRedis:/data/
    networks:
      - backend_redis

networks:
  backend_redis:
  webserver:
